import React, { Component } from 'react';
import Svg,{
  Circle,
  Ellipse,
  G,
  LinearGradient,
  RadialGradient,
  Line,
  Path,
  Polygon,
  Polyline,
  Rect,
  Symbol,
  Text,
  Use,
  Defs,
  Stop
} from 'react-native-svg';
export default class Stroke extends Component {
  render () {
    return (
      <Svg height="40" width="40">
        <Line
          x1="0"
          y1="0"
          x2="600"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>

        <Line
          x1="0"
          y1="0"
          x2="700"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>

        <Line
          x1="0"
          y1="0"
          x2="200"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="250"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="400"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>

        <Line
          x1="0"
          y1="0"
          x2="160"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="150"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="130"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="110"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="90"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="80"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="70"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="60"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="50"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="40"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="30"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="20"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="10"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
        <Line
          x1="0"
          y1="0"
          x2="5"
          y2="100"
          stroke={this.props.color}
          strokeWidth="2"/>
      </Svg>
    )
  }

  shouldComponentUpdate () {
    return false;
  }
}